# AUTO-GENERATED by scripts/launch/openpi_profile.py. DO NOT EDIT BY HAND.
# Delete this file to revert OpenPI to upstream-only configs.
"""Evo-RL-Piper auto-generated TrainConfigs.

Loaded by config.py via the evorl-auto-config try-import hook.
"""

from . import config as _c
from . import weight_loaders
from .config import (
    DataConfig,
    LeRobotWbcdPiperXDataConfig,
    TrainConfig,
)
from .. import transforms as _transforms
from ..models import pi0_config

_AUTO_CONFIGS = [
    TrainConfig(
        name="auto__piper_x_left_0519_10points_piper_x_left_0519_10points_left__lora",
        model=pi0_config.Pi0Config(
            pi05=True,
            action_horizon=10,
            paligemma_variant="gemma_2b_lora",
            action_expert_variant="gemma_300m_lora",
        ),
        data=LeRobotWbcdPiperXDataConfig(
            repo_id="piper_x_left_0519_10points/piper_x_left_0519_10points",
            adapt_to_pi=False,
            repack_transforms=_transforms.Group(
                inputs=[
                    _transforms.RepackTransform(
                        {
                            "images": {
                                "cam_high": "observation.images.head_cam",
                                "cam_under": "observation.images.under_view_cam",
                                "cam_active_wrist": "observation.images.right_wrist_cam",
                            },
                            "state": "agent_pos",
                            "actions": "action",
                        }
                    )
                ]
            ),
            base_config=DataConfig(
                prompt_from_task=False,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader(
            "gs://openpi-assets/checkpoints/pi05_base/params"
        ),
        freeze_filter=pi0_config.Pi0Config(
            pi05=True,
            paligemma_variant="gemma_2b_lora",
            action_expert_variant="gemma_300m_lora",
        ).get_freeze_filter(),
        num_train_steps=30_000,
        batch_size=64,
        fsdp_devices=4,
        ema_decay=None,
    ),
    TrainConfig(
        name="auto__wbcd_piper_x_dual_0518_0519_zipper_active__lora",
        model=pi0_config.Pi0Config(
            pi05=True,
            action_horizon=10,
            paligemma_variant="gemma_2b_lora",
            action_expert_variant="gemma_300m_lora",
        ),
        data=LeRobotWbcdPiperXDataConfig(
            repo_id="WBCD/piper_x_dual_0518_0519_zipper",
            adapt_to_pi=False,
            repack_transforms=_transforms.Group(
                inputs=[
                    _transforms.RepackTransform(
                        {
                            "images": {
                                "cam_high": "observation.images.head_cam",
                                "cam_under": "observation.images.under_view_cam",
                                "cam_active_wrist": "observation.images.right_wrist_cam",
                            },
                            "state": "agent_pos",
                            "actions": "action",
                            "prompt": "prompt",
                        }
                    )
                ]
            ),
            base_config=DataConfig(
                prompt_from_task=True,
            ),
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader(
            "gs://openpi-assets/checkpoints/pi05_base/params"
        ),
        freeze_filter=pi0_config.Pi0Config(
            pi05=True,
            paligemma_variant="gemma_2b_lora",
            action_expert_variant="gemma_300m_lora",
        ).get_freeze_filter(),
        num_train_steps=30_000,
        batch_size=64,
        fsdp_devices=4,
        ema_decay=None,
    ),
]
